title: Taehyung Kim # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Developer
  <br><br>
  Highly accomplished, multifaceted developer with over four years of experience for a private company and seven years at the Republic of Korea Army, seeking a <b>Back-End and Front-End Developer position.</b> Internet Applications and Web Development studies in Canada and a bachelor’s degree in Computer Science in Korea
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
