title: Taehyung Kim # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Experienced Developer</b><br>
  <a href="mailto:taehyungkim@outlook.com">taehyungkim@outlook.com</a>
  <br><br>
  Azure, SQL, Javascript, PHP, Node.js, Lalavel, AWS, Travis
  <br><br>
  Highly accomplished, multifaceted developer with over four years of experience for a private company and seven years at the Republic of Korea Army. 
  <br>
  Internet Applications and Web Development studies in London, ON and a bachelor’s degree in Computer Science in Korea
  <br><br>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="951dd854-bba7-4416-8004-51434e2fe612" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  <br><br>
  <img src="images/resume.jpeg?raw=true" width="15px"/><a href='/pdf/Taehyung_Resume.pdf'> <b>Resume</b></a><br><br>
  <a href='https://ca.linkedin.com/in/taehyungalexkim/en-us?trk=profile-badge' target="_blank"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" /></a>

theme: jekyll-theme-minimal
google_analytics: UA-197826232-1 # your Google Analytics tracking ID here
