title: Taehyung Kim # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Database Administrator</b><br>
  <a href="mailto:taehyungkim@outlook.com">taehyungkim@outlook.com</a>
  <br>
  Richmond School District No.38
  <br><br>
  Power platform, Manufacturing Execution System, Azure, SQL, Javascript, PHP, Node.js, Lalavel, AWS, Travis
  <br><br>
  Diploma in Internet Applications and Web Development in London, ON and a bachelor’s degree in Computer Science in Korea
  <br><br>
  <a href='https://ca.linkedin.com/in/taehyungalexkim/en-us?trk=profile-badge' target="_blank"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" /></a>
  <br>
  <div data-iframe-width="130" data-iframe-height="270" data-share-badge-id="91b9db8f-fa0b-42eb-a1de-df0805fce4db" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  <div data-iframe-width="130" data-iframe-height="270" data-share-badge-id="951dd854-bba7-4416-8004-51434e2fe612" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>

theme: jekyll-theme-minimal
google_analytics: UA-197826232-1 # your Google Analytics tracking ID here
